# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIPs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ippublica', models.TextField(max_length=16)),
                ('ipprivada', models.TextField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TablaIntermedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RegistroIPs')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
